server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /catalog/ {
    rewrite ^/catalog/(.*)$ /$1 break;
    proxy_pass http://catalog-service:18081;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /inventory/ {
    rewrite ^/inventory/(.*)$ /$1 break;
    proxy_pass http://inventory-service:18082;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /orders/ {
    rewrite ^/orders/(.*)$ /$1 break;
    proxy_pass http://order-service:18083;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /payment/ {
    rewrite ^/payment/(.*)$ /$1 break;
    proxy_pass http://payment-service:18084;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/orders {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/admin/ {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /promotion/ {
    rewrite ^/promotion/(.*)$ /$1 break;
    proxy_pass http://promotion-service:18085;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/admin/outbox-services/ {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/admin/coupon-usages {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/admin/fulfillment-requests {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/read-model/ {
    proxy_pass http://gateway:18080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
